BIN = hellot
CC = clang
FLAGS = -std=c99 -DAPPLE -Wall -pedantic -Wextra
INC = -I/sw/include -I/opt/homebrew/include
LIBS = -lGLEW -lglfw -L/opt/homebrew/lib
FRAMEWORKS = -framework Cocoa -framework OpenGL -framework IOKit
SRC = main.c

all:
	${CC} ${FLAGS} ${FRAMEWORKS} -o ${BIN} ${SRC} ${INC} ${LIBS}


