BIN = raypick
CC = clang++
FLAGS = -DAPPLE -Wall -pedantic
INC = -I ../common/include -I/sw/include -I/usr/local/include
LIB_PATH = ../common/osx_64/
LOC_LIB = $(LIB_PATH)libGLEW.a $(LIB_PATH)libglfw3.a
FRAMEWORKS = -framework Cocoa -framework OpenGL -framework IOKit
SRC = main.cpp gl_utils.cpp maths_funcs.cpp obj_parser.cpp

all:
	${CC} ${FLAGS} ${FRAMEWORKS} -o ${BIN} ${SRC} ${INC} ${LOC_LIB}

