CC = clang++
FLAGS = -DAPPLE -Wall -pedantic
INC = -I/sw/include -I/usr/local/include -I/usr/local/include/freetype2/ -I/opt/homebrew/include
LIBS = -L /opt/homebrew/lib -lGLEW -lglfw
FRAMEWORKS = -framework Cocoa -framework OpenGL -framework IOKit
SRC = main.cpp maths_funcs.cpp 

all: generator viewer

generator:
	${CC} ${FLAGS} -o generate generator_main.cpp  ${INC} -lfreetype

viewer:
	${CC} ${FLAGS} ${FRAMEWORKS} -o view viewer_main.cpp maths_funcs.cpp  ${INC} ${LIBS}
