BIN = pick
CC = g++ -g
FLAGS = -Wall -pedantic -g
INC = -I ../common/include
LOC_LIB = ../common/linux_i386/libGLEW.a -lglfw ../common/linux_i386/libassimp.a
SYS_LIB = -lGL  -lz
SRC = main.cpp maths_funcs.cpp gl_utils.cpp obj_parser.cpp

all:
	${CC} ${FLAGS} -o ${BIN} ${SRC} ${INC} ${LOC_LIB} ${SYS_LIB}

