BIN   = skin
CC    = g++
FLAGS = -Wall -pedantic
LIBS  = -lGLEW -lglfw -lassimp -lGL
SRC   = main.cpp gl_utils.cpp maths_funcs.cpp

all:
	$(CC) $(FLAGS) -o $(BIN) $(SRC) $(LIBS)

clean:
	rm -rf $(BIN)
