BIN = hellot
CC = clang
FLAGS = -std=c99 -DAPPLE -Wall -pedantic
INC = -I/sw/include -I/usr/local/include
LIBS = -lGLEW -lglfw
FRAMEWORKS = -framework Cocoa -framework OpenGL -framework IOKit
SRC = main.c

all:
	${CC} ${FLAGS} ${FRAMEWORKS} -o ${BIN} ${SRC} ${INC} ${LIBS}

