BIN = hellot
CC = gcc
#FLAGS = -Wall -pedantic
INC = -I ../common/include
LOC_LIB = ../common/linux_i386/libGLEW.a -lglfw
SYS_LIB = -lGL -lm
SRC = main.c

all:
	${CC} ${FLAGS} -o ${BIN} ${SRC} ${INC} ${LOC_LIB} ${SYS_LIB}

