BIN = hellot
CC = gcc
#FLAGS = -Wall -pedantic
INC = -I ../common/include
LOC_LIB = ../common/linux_i386/libGLEW.a ../common/linux_i386/libglfw3.a
SYS_LIB = -lGL -lX11 -lXxf86vm -lXrandr -lpthread -lXi -lm
SRC = main.c

all:
	${CC} ${FLAGS} -o ${BIN} ${SRC} ${INC} ${LOC_LIB} ${SYS_LIB}

