BIN = cubemap
CC = g++
FLAGS = -Wall -pedantic
INC = -I ../common/include
LIB_DIR = ../common/linux_i386/
LOC_LIB = $(LIB_DIR)libGLEW.a $(LIB_DIR)libglfw3.a $(LIB_DIR)libassimp.a
SYS_LIB = -lGL -lX11 -lXxf86vm -lXrandr -lpthread -lXi -lz
SRC = main.cpp maths_funcs.cpp gl_utils.cpp stb_image.c obj_parser.cpp

all:
	${CC} ${FLAGS} -o ${BIN} ${SRC} ${INC} ${LOC_LIB} ${SYS_LIB}

