BIN = skin
CC = clang++
FLAGS = -DAPPLE -Wall -pedantic -std=c++11
INC = -I/sw/include -I/usr/local/include
LIBS = -lGLEW -lglfw -lassimp
FRAMEWORKS = -framework Cocoa -framework OpenGL -framework IOKit
SRC = main.cpp maths_funcs.cpp gl_utils.cpp

all:
	${CC} ${FLAGS} ${FRAMEWORKS} -o ${BIN} ${SRC} ${INC} ${LOC_LIB} ${LIBS}

