BIN = quats
CC = clang++
FLAGS = -DAPPLE -Wall -pedantic
INC = -I/sw/include -I/opt/homebrew/include
LIBS = -lGLEW -lglfw -L/opt/homebrew/lib
FRAMEWORKS = -framework Cocoa -framework OpenGL -framework IOKit
SRC = main.cpp gl_utils.cpp maths_funcs.cpp obj_parser.cpp

all:
	${CC} ${FLAGS} ${FRAMEWORKS} -o ${BIN} ${SRC} ${INC} ${LIBS}

