BIN = fog
CC = clang++
FLAGS = -DAPPLE -Wall -pedantic -std=c++11
INC = -I/sw/include -I/opt/homebrew/include
LIBS = -lGLEW -lglfw -L/opt/homebrew/lib -lassimp
FRAMEWORKS = -framework Cocoa -framework OpenGL -framework IOKit
SRC = main.cpp maths_funcs.cpp gl_utils.cpp

all:
	${CC} ${FLAGS} ${FRAMEWORKS} -o ${BIN} ${SRC} ${INC} ${LIBS}

