BIN = cubemap
CC = g++
FLAGS = -Wall -pedantic
LIBS = -lGLEW -lglfw -lassimp -lGL
SRC = main.cpp maths_funcs.cpp gl_utils.cpp obj_parser.cpp

all:
	${CC} ${FLAGS} -o ${BIN} ${SRC} ${INC} ${LOC_LIB} ${LIBS}

