BIN = extinit
CC = clang
FLAGS = -std=c99 -DAPPLE -Wall -pedantic
INC = -I/sw/include -I/usr/local/include -I/opt/homebrew/include
LIBS = -L /opt/homebrew/lib -lGLEW -lglfw
FRAMEWORKS = -framework Cocoa -framework OpenGL -framework IOKit
SRC = main.c

all:
	${CC} ${FLAGS} ${FRAMEWORKS} -o ${BIN} ${SRC} ${INC} ${LIBS}

