BIN = skin
CC = g++ -g
FLAGS = -Wall -pedantic -g
INC = -I ../common/include
LP = ../common/linux_i386/
LOC_LIB = ${LP}libGLEW.a ${LP}libglfw3.a ${LP}libassimp.a
SYS_LIB = -lGL -lX11 -lXxf86vm -lXrandr -lpthread -lXi -lz
SRC = main.cpp maths_funcs.cpp gl_utils.cpp

all:
	${CC} ${FLAGS} -o ${BIN} ${SRC} ${INC} ${LOC_LIB} ${SYS_LIB}

